[Variables]

Location=INXX0074
Unit=m
ScrollMouseIncrement=0.05
Format=#I
Hidden=1
Hidden2=0
Player=Spotify
Color1=255,255,255
Color2=255,187,64
Color3=0,0,0
UserName=Rayyan

;NOTES:

;This below is the settings for the dock with icons.
;If you are not familiar with Rainmeter from earlier,please don't edit anything!
;It's too complicated and sensitive,if you don't know what you doing!
;But i will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,new icon-s,you must put in "@Resources" folder.Also,icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:

;This is example for some program:

;
;Name1=CCleaner
;TextName1=CCleaner
;LocationPath1=["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Name2=Twitter
;TextName2=Twitter
;LocationPath2=["https://twitter.com/?lang=en"]

;etc..

;----------------------Icon Dock Settings--------------------------
;------------------------------------------------------------------


Icon1NameAndPath=#@#\Email.png
TextName1=Email
LocationPath1=["https://mail.google.com/mail/"]

Icon2NameAndPath=#@#\GitHub.png
TextName2=GitHub
LocationPath2=["https://github.com/dashboard"]

Icon3NameAndPath=#@#\Music.png
TextName3=Spotify
LocationPath3=["C:\Users\moham\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Spotify.lnk"]

Icon4NameAndPath=#@#\Picture.png
TextName4=Monkeytype
LocationPath4=["https://monkeytype.com/"]

Icon5NameAndPath=#@#\Video.png
TextName5=Android 
LocationPath5=["C:\Users\moham\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Android Studio.lnk"]

Icon6NameAndPath=#@#\Chrome.png
TextName6=Chrome
LocationPath6=["C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Google Chrome.lnk"]

Icon7NameAndPath=#@#\Twitter.png
TextName7=VS Code
LocationPath7=["C:\Users\moham\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code\Visual Studio Code.lnk"]


